### ISSUE TITLE
Error after images generations.

### ISSUE THREAD

**Issue by OofasTheOld** [Xerxemi/sdweb-auto-MBW#10]
After the images are generated, i got this error :

Traceback (most recent call last):
  File "F:\automatic1111\01\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\automatic1111\01\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "F:\automatic1111\01\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\automatic1111\01\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\automatic1111\01\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\automatic1111\01\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\automatic1111\01\extensions\sdweb-auto-MBW\scripts\mbw\auto_mbw.py", line 679, in onclick_btn_do_merge_block_weighted
    binary_mid_pass(prechks, 1)
  File "F:\automatic1111\01\extensions\sdweb-auto-MBW\scripts\mbw\auto_mbw.py", line 646, in binary_mid_pass
    lowerscore = merge_wrapper(merge_params)
  File "F:\automatic1111\01\extensions\sdweb-auto-MBW\scripts\mbw\auto_mbw.py", line 425, in merge_wrapper
    images = txt2img(model=model_O,
  File "F:\automatic1111\01\extensions\sdweb-auto-MBW\scripts\util_autombw\txt2img_api.py", line 43, in txt2img
    for i in r['images']:
KeyError: 'images'

Not really sure if I'm using bad parameter or if I'm missing something.

**Comment by xdomiall** [comment]
has anyone ever solved this?

**Comment by xdomiall** [comment]
lol, solved it by giving the output model a name, must hit some exception with the default name
