### ISSUE TITLE
Not working in A1111 (15th September 2023)

### ISSUE THREAD

**Issue by oliverban** [Xerxemi/sdweb-auto-MBW#21]
*** Error loading script: auto_mbw_extension.py
    Traceback (most recent call last):
      File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\extensions\auto-MBW-rt\scripts\auto_mbw_extension.py", line 6, in <module>
        from scripts.main import mbw as auto_mbw
      File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\extensions\auto-MBW-rt\scripts\main\mbw.py", line 29, in <module>
        from scripts.main.merger import handle_model_load, disable_injection, adjust_weights_score, save_checkpoint
      File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\extensions\auto-MBW-rt\scripts\main\merger.py", line 31, in <module>
        from scripts.runtime_block_merge import on_save_checkpoint
    ModuleNotFoundError: No module named 'scripts.runtime_block_merge'

I've tried manually installing dependencies but same error.

**Comment by zcatharisis** [comment]
Just installed it and the only issue I encountered was ImportError: cannot import name 'wrap_gradio_gpu_call' from 'webui' 
Fixed it by following this code change from the Deforum github https://github.com/deforum-art/sd-webui-deforum/pull/867
